### ISSUE TITLE
Different outputs between rest API and list asset command

### ISSUE THREAD

**Issue by javiervargas** [lightninglabs/taro#247] opened 2023-01-28 15:14 UTC
Hi,

I am getting different results between the assets list command and the same one using the rest API. Is there a conversion to do?

Command -> genesis_bootstrap_info: e588580e1e95f84db1f3216b55142c29880216d25d86a10361e019f9a64bc68e000000010a74657374636f696e3139000000000000

API -> genesis_bootstrap_info : 5YhYDh6V+E2x8yFrVRQsKYgCFtJdhqEDYeAZ+aZLxo4AAAABCnRlc3Rjb2luMTkAAAAAAAA=

`ubuntu@vps-a68e990f:~$ tarocli assets list`

`  {
            "version": 0,
            "asset_genesis": {
                "genesis_point": "8ec64ba6f919e06103a1865dd2160288292c14556b21f3b14df8951e0e5888e5:1",
                "name": "testcoin19",
                "meta": null,
                "asset_id": "28a52c64dab65a77791fff8be43e465b57f2b79b1823cc07e287900265d504ed",
                "output_index": 0,
                "genesis_bootstrap_info": "e588580e1e95f84db1f3216b55142c29880216d25d86a10361e019f9a64bc68e000000010a74657374636f696e3139000000000000",
                "version": 0
            },
            "asset_type": "NORMAL",
            "amount": "100",
            "lock_time": 0,
            "relative_lock_time": 0,
            "script_version": 0,
            "script_key": "02cf36b1aa0d9c9511f545ac6aef14c7a7e1bd1d41a15e48fd1e69745e4c8327e4",
            "asset_group": null,
            "chain_anchor": {
                "anchor_tx": "02000000000101e588580e1e95f84db1f3216b55142c29880216d25d86a10361e019f9a64bc68e0100000000ffffffff02e803000000000000225120342694d934101127c85c06e9ef9385fe88fbc178f30f1b55747cc372c619e56137fe0e000000000016001430ec2544a36e75a59a702e62f8a5189299cb686e02473044022056277ef76c91afcfc756fb1d4c64531b049e7d7e7bdbb4f25fbdea1990405c7b0220266847b42889fbcf83abefb3161bfc63d6697da543f1f1946c2cd66c68a9fc3001210206073891b1f79a34fd15491d87b43a4e86c5ae6e36b1b21f402979d755589e3a00000000",
                "anchor_txid": "fdeb3264426e48f8c64e42e9a930b745a43e56ae688ff33a79caa23ba2a3a0b1",
                "anchor_block_hash": "0000000000000000000000000000000000000000000000000000000000000000",
                "anchor_outpoint": "fdeb3264426e48f8c64e42e9a930b745a43e56ae688ff33a79caa23ba2a3a0b1:0",
                "internal_key": "033315aa406dcb92602c15d6ca45f8586d299606f7fd8e6d21415f2e29867e3645"
            }
        }
    ]
}`

API rest

`curl --insecure --header "Grpc-Metadata-macaroon: XXX" -X GET https://127.0.0.1:8089/v1/taro/assets`

`{
		"version": 0,
		"asset_genesis": {
			"genesis_point": "8ec64ba6f919e06103a1865dd2160288292c14556b21f3b14df8951e0e5888e5:1",
			"name": "testcoin19",
			"meta": "",
			"asset_id": "KKUsZNq2Wnd5H/+L5D5GW1fyt5sYI8wH4oeQAmXVBO0=",
			"output_index": 0,
			"genesis_bootstrap_info": "5YhYDh6V+E2x8yFrVRQsKYgCFtJdhqEDYeAZ+aZLxo4AAAABCnRlc3Rjb2luMTkAAAAAAAA=",
			"version": 0
		},
		"asset_type": "NORMAL",
		"amount": "100",
		"lock_time": 0,
		"relative_lock_time": 0,
		"script_version": 0,
		"script_key": "As82saoNnJUR9UWsau8Ux6fhvR1BoV5I/R5pdF5Mgyfk",
		"asset_group": null,
		"chain_anchor": {
			"anchor_tx": "AgAAAAABAeWIWA4elfhNsfMha1UULCmIAhbSXYahA2HgGfmmS8aOAQAAAAD/////AugDAAAAAAAAIlEgNCaU2TQQESfIXAbp75OF/oj7wXjzDxtVdHzDcsYZ5WE3/g4AAAAAABYAFDDsJUSjbnWlmnAuYvilGJKZy2huAkcwRAIgVid+92yRr8/HVvsdTGRTGwSefX5727TyX73qGZBAXHsCICZoR7QoifvPg6vvsxYb/GPWaX2lQ/HxlGws1mxoqfwwASECBgc4kbH3mjT9FUkdh7Q6TobFrm42sbIfQCl511VYnjoAAAAA",
			"anchor_txid": "fdeb3264426e48f8c64e42e9a930b745a43e56ae688ff33a79caa23ba2a3a0b1",
			"anchor_block_hash": "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA=",
			"anchor_outpoint": "fdeb3264426e48f8c64e42e9a930b745a43e56ae688ff33a79caa23ba2a3a0b1:0",
			"internal_key": "AzMVqkBty5JgLBXWykX4WG0plgb3/Y5tIUFfLimGfjZF"
		}
	}]
}`

Thanks!
J

**Comment by guggero** [comment] 2023-01-30 09:28
That's just because the REST API by default encodes binary (`bytes`) fields as base64 while the command line interface uses hex encoding by default. These are easily convertible.
This is how all our REST APIs work (`lnd`, Loop, Pool, Faraday), so I'm going to close this as "works as intended".

**Closed by guggero** 2023-01-30 09:28 UTC
